@startsalt
skinparam dpi 300
skinparam handwritten true
skinparam Backgroundcolor white
{SI
{+
{* <&play-circle><b>TV Guide }
.
{+
<&magnifying-glass>                      Search Your Favourite TV Show                      <&magnifying-glass>
}
.
{* < | <b>Today | > | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | Country: | US
 US | AU | BR | CN | DE | NL | TR | UK }
.
{T-
+           | 20:00 | 21:00 | 22:00
.
+ <b>Action | Crashing Cars | Jumping from Planes | Shooting
.
+ <b>Comedy | Ricky | Gervais | Show
.
+ <b>Drama  | Crying Men | Clash of Sitars | Drammm
.
}
}
}
@endsalt